# Generated by Django 4.1.6 on 2023-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_model',
            name='image',
            field=models.ImageField(default='no_image', upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
